workflows:
  ios-release-workflow:
    name: Build iOS Release (Harikar)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Generate iOS Podfile and CocoaPods files
        script: flutter build ios --no-codesign

      - name: Set up keychain for code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.heamasoft.harikar" --type IOS_APP_STORE
          keychain add-certificates

      - name: Build .ipa for release
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - heama.soft@gmail.com
